### PR TITLE
Fix build error

### PR DESCRIPTION
**Pull request by cewert**
This fixes the build error I ran into.

docker-build-error

docker-build-error-fixed

### CODE REVIEW

**Comment by wolkenschieber** [comment]
Thanks for submitting the pull request!

Unfortunately I cannot reproduce the issue, also I haven't seen commands wrapped around in their own subshell.

Do you have any documentation on this or a hint which would help me understand the scenario?

**Comment by cewert** [comment]
I don't have a link to the docs but you'll notice that the original run command was being converted to using it's own subshell in my error message `/bin/sh -c chmod +w /etc/chromium/policies/managed`. My PR just changes it to use /bin/bash instead `/bin/bash -c chmod +w /etc/chromium/policies/managed`

I should have mentioned I was running ubuntu when I ran into the error. I'm guessing you can't reproduce because you are building with a different distro?

**Comment by wolkenschieber** [comment]
I'm building the image using Arch. You are right about the conversion: `RUN` uses `/bin/sh -c` per default[1](https://docs.docker.com/engine/reference/builder/#run). 

I'm confused where the error is happening. Until this PR I was convinced, that `RUN` executes the following command from the image in the image. However I'm not sure since there's a shell involved.

Can you check whether you have a `/bin/sh` on your system?

If we want to change the shell for the commands, we should opt for [SHELL](https://docs.docker.com/engine/reference/builder/#shell) and set
```Dockerfile
SHELL ["/bin/bash", "-c"]
```

What do you think?

**Comment by cewert** [comment]
> Can you check whether you have a `/bin/sh` on your system?

I'm using a headless ubuntu server 22.04 LTS which uses dash for /bin/sh I believe.
Edit: Just checked and yea it's dash `0 lrwxrwxrwx 1 root root 4 Mar 23  2022 /bin/sh -> dash`

> If we want to change the shell for the commands, we should opt for [SHELL](https://docs.docker.com/engine/reference/builder/#shell) and set
> 
> ```dockerfile
> SHELL ["/bin/bash", "-c"]
> ```
> 
> What do you think?

Makes sense to me and is a better solution than the one in this PR since the shell command would proactively prevent any more shell issues with future commands.

PS: Do you know how to enable support for casting/mDNS? I've tried rebasing on ubuntu with some added packages and toggling chrome:// flags but no luck. My goal is to self host this image on my network, open chromium in a browser, cast the webpage to a chromecast on my network, then close the tab and have everything work as expected.

**Comment by wolkenschieber** [comment]
> Makes sense to me and is a better solution than the one in this PR since the shell command would proactively prevent any more shell issues with future commands.

Great. Let's go for this option!

> PS: Do you know how to enable support for casting/mDNS? I've tried rebasing on ubuntu with some added packages and toggling chrome:// flags but no luck. My goal is to self host this image on my network, open chromium in a browser, cast the webpage to a chromecast on my network, then close the tab and have everything work as expected.

I'm not familiar with casting. If it's a policy controlled option, you'll find it in the [Chrome docs](https://chromeenterprise.google/policies/). Searching for _cast_ brings up [MediaRouterCastAllowAllIPs](https://chromeenterprise.google/policies/#MediaRouterCastAllowAllIPs). Could be worth invesitgating.

**Comment by cewert** [comment]
FYI for anyone reading this in the future: to enable casting support you need to set `network_mode` to `host`. Can't believe it took me this long to try that 🙈

**Pull request merged**
